	@echo off

	@REM set EXECUTION_COMMAND=mvnw spring-boot:run --quiet
	set EXECUTION_COMMAND=java -Xms128M -jar target\locations-finder-1.0.jar 

	@REM set LOCATIONS_FINDER_INPUT_SRID=26918
	set LOCATIONS_FINDER_AUTO_OFFSET_RESET_CONFIG=earliest
	@REM set LOCATIONS_FINDER_DEBUG_TRIGGER_REBALANCING_ON_STARTUP_AFTER_MINUTES=3

	set LOCATIONS_FINDER_DELAY_FOR_MISSING_CITY_IN_SEC=120
	set LOCATIONS_FINDER_SESSION_TIMEOUT_SECONDS_CONFIG=120

	@echo on

	call set-env.cmd
	call ../delay-manager/set-env.cmd
	call ../activity-aggregator/set-env.cmd
	@REM set LOCATIONS_FINDER_CONSUMER_THREADS_COUNT=5

    set LOCATIONS_FINDER_INPUT_TOPIC=%PEDESTRIANS_GEO_LOCATIONS_TOPIC%
	set LOCATIONS_FINDER_OUTPUT_TOPIC=%PEDESTRIANS_STREETS_TOPIC%
	set LOCATIONS_FINDER_LOCATION_TYPE=street
	for /l %%i in (1,1,1) do start /B  %EXECUTION_COMMAND%

    set LOCATIONS_FINDER_INPUT_TOPIC=%PEDESTRIANS_GEO_LOCATIONS_TOPIC%
	set LOCATIONS_FINDER_OUTPUT_TOPIC=%PEDESTRIANS_NEIGHBORHOODS_TOPIC%
	set LOCATIONS_FINDER_LOCATION_TYPE=neighborhood
	for /l %%i in (1,1,1) do start /B  %EXECUTION_COMMAND%

    set LOCATIONS_FINDER_INPUT_TOPIC=%MOBILIZED_GEO_LOCATIONS_TOPIC%
	set LOCATIONS_FINDER_OUTPUT_TOPIC=%MOBILIZED_STREETS_TOPIC%
	set LOCATIONS_FINDER_LOCATION_TYPE=street
	for /l %%i in (1,1,1) do start /B  %EXECUTION_COMMAND%

    set LOCATIONS_FINDER_INPUT_TOPIC=%MOBILIZED_GEO_LOCATIONS_TOPIC%
	set LOCATIONS_FINDER_OUTPUT_TOPIC=%MOBILIZED_NEIGHBORHOODS_TOPIC%
	set LOCATIONS_FINDER_LOCATION_TYPE=neighborhood
	for /l %%i in (1,1,1) do start /B  %EXECUTION_COMMAND%
