version: '3'

services:
  mobilization-classifier:
    image: erancha/urbangeopulse:mobilization-classifier-1.0
    networks:
      - urbangeopulse-net
    env_file:
      - ./kafka-vars.env
    environment:
      REDIS_HOST_NAME: redis-server

      # TODO: Try to reuse env variables as in basic-implementation\scripts\development

      MOBILIZATION_CLASSIFIER_AUTO_OFFSET_RESET_CONFIG: earliest
      MOBILIZATION_CLASSIFIER_SESSION_TIMEOUT_SECONDS_CONFIG: 120
    depends_on:
      - kafka-broker

networks:
  urbangeopulse-net:
    external:
      name: urbangeopulse-net
