version: '3'

services:
  locations-finder-pedestrians-streets:
    image: erancha/urbangeopulse:locations-finder-1.0
    networks:
      - urbangeopulse-net
    env_file:
      - ./kafka-vars.env
      - ./pg-vars.env
      - ./locations-finder-vars.env
    environment:
      # TODO: Try to reuse env variables as in basic-implementation\scripts\development
    depends_on:
      - kafka-broker
      - postgis-server-nyc

  locations-finder-pedestrians-neighborhoods:
    image: erancha/urbangeopulse:locations-finder-1.0
    networks:
      - urbangeopulse-net
    env_file:
      - ./kafka-vars.env
      - ./pg-vars.env
      - ./locations-finder-vars.env
    environment:
      # TODO: Try to reuse env variables as in basic-implementation\scripts\development
    depends_on:
      - kafka-broker
      - postgis-server-nyc

  locations-finder-mobilized-streets:
    image: erancha/urbangeopulse:locations-finder-1.0
    networks:
      - urbangeopulse-net
    env_file:
      - ./kafka-vars.env
      - ./pg-vars.env
      - ./locations-finder-vars.env
    environment:
      # TODO: Try to reuse env variables as in basic-implementation\scripts\development
    depends_on:
      - kafka-broker
      - postgis-server-nyc

  locations-finder-mobilized-neighborhoods:
    image: erancha/urbangeopulse:locations-finder-1.0
    networks:
      - urbangeopulse-net
    env_file:
      - ./kafka-vars.env
      - ./pg-vars.env
      - ./locations-finder-vars.env
    environment:
      # TODO: Try to reuse env variables as in basic-implementation\scripts\development
    depends_on:
      - kafka-broker
      - postgis-server-nyc

networks:
  urbangeopulse-net:
    external:
      name: urbangeopulse-net
