version: '3'

services:
  receiver:
    image: erancha/urbangeopulse:receiver-1.0
    ports:
      - "8080:8080"
    networks:
      - urbangeopulse-net
    env_file:
      - ./kafka-vars.env
      - ./pg-vars.env
    environment:
      PEOPLE_GEO_LOCATIONS_TOPIC_NAME: people_geo_locations
      COPY_FROM_BACKUP: 1*1000
      PEOPLE_GEO_LOCATIONS_CSV: people-geo-locations--Duffield_St.csv
    depends_on:
      - kafka-broker
      - postgis-server-nyc

  info:
    image: erancha/urbangeopulse:info-1.0
    ports:
      - "8081:8081"
    networks:
      - urbangeopulse-net
    env_file:
      - ./pg-vars.env
    depends_on:
      - postgis-server-nyc

networks:
  urbangeopulse-net:
    external:
      name: urbangeopulse-net
