version: '3.8'

networks:
  urbangeopulse-net:
    external: true
    name: urbangeopulse-net

services:
  kafka:
    image: confluentinc/cp-kafka:6.0.14
    hostname: kafka
    depends_on:
      - kafka-zookeeper
    networks:
      - urbangeopulse-net
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
      - target: 29092
        published: 29092
        protocol: tcp
        mode: host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR

  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:6.0.14
    hostname: kafka-zookeeper
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    networks:
      - urbangeopulse-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-ui:
    image: provectuslabs/kafka-ui:333eae24759aaa7b3fc14e5e7dea232200c13dcd
    depends_on:
      - kafka
    networks:
      - urbangeopulse-net
    ports:
      - target: 8080
        published: 7070
        protocol: tcp
        mode: host
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-zookeeper:2181
      LOGGING_LEVEL_ROOT: error
      LOGGING_LEVEL_COM_PROVECTUS: error

  redis-server:
    image: redis:7.0-alpine
    networks:
      - urbangeopulse-net
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

  postgis-server-nyc:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=nyc
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    networks:
      - urbangeopulse-net

  pgadmin-server:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadminpass
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: host
    networks:
      - urbangeopulse-net
