version: '3'

services:
  receiver:
    image: erancha/urbangeopulse:receiver-latest
    ports:
      - "8080:8080"
    networks:
      - urbangeopulse-net
    env_file:
      - ./shared-env/postgres-access-vars.env
      - ./shared-env/pipeline-vars.env
      - ./shared-env/mobilization-classifier-vars.env
    environment:
      PEOPLE_GEO_LOCATIONS_CSV: /app/NYC_people-geo-locations--all.csv
      # PEOPLE_GEO_LOCATIONS_CSV: /app/NYC_people-geo-locations--Duffield_St.csv
      SIMULATOR_ITERATIONS_FROM_BACKUP: 20
      SIMULATOR_THROTTLE_THROUGHPUT_PRODUCING: 1000
      SIMULATOR_INCREMENT_EACH_N_ITERATIONS: 5
      SIMULATOR_INCREMENT_VALUE: 500
    depends_on:
      - kafka-broker
      - postgis-server-nyc

networks:
  urbangeopulse-net:
    external: true
