version: '3'

services:
  info:
    image: erancha/urbangeopulse:info-mongodb
    ports:
      - "8081:8081"
    networks:
      - urbangeopulse-net
    env_file:
      - ./shared-env/mongodb-access-vars.env
      - ./shared-env/postgres-access-vars.env
      - ./shared-env/pipeline-vars.env
    depends_on:
      - mongodb-server
      - postgis-server-nyc

networks:
  urbangeopulse-net:
    external: true
