version: '3'

services:
  mobilization-classifier:
    image: erancha/urbangeopulse:mobilization-classifier-1.1
    networks:
      - urbangeopulse-net
    env_file:
      - ./shared-env/pipeline-vars.env
      - ./shared-env/mobilization-classifier-vars.env
      - ./shared-env/locations-finder-vars-cross-service.env
    environment:
      REDIS_HOST_NAME: redis-server
      MOBILIZATION_CLASSIFIER_AUTO_OFFSET_RESET_CONFIG: earliest
      MOBILIZATION_CLASSIFIER_SESSION_TIMEOUT_SECONDS_CONFIG: 120
    depends_on:
      - kafka-broker
      - redis-server

networks:
  urbangeopulse-net:
    external: true
