version: '3'

services:
  info-postgres:
    image: erancha/urbangeopulse:info-postgres
    ports:
      - "8082:8081"
    networks:
      - urbangeopulse-net
    env_file:
      - ./shared-env/postgres-access-vars.env
      - ./shared-env/pipeline-vars.env
    depends_on:
      - postgis-server-nyc

networks:
  urbangeopulse-net:
    external: true
