@echo off

@REM set EXECUTION_COMMAND=mvnw spring-boot:run --quiet
set EXECUTION_COMMAND=java -Xms128M -jar target\activity-aggregator-1.0.jar 

set ACTIVITY_AGGREGATOR_AUTO_OFFSET_RESET_CONFIG=earliest
@REM set ACTIVITY_AGGREGATOR_DEBUG_TRIGGER_REBALANCING_ON_STARTUP_AFTER_MINUTES=1
@REM set ACTIVITY_AGGREGATOR_PERSISTENCE_MAX_RECORDS=100

@REM set ACTIVITY_AGGREGATOR_MAX_POLL_INTERVAL_MINUTES_CONFIG=10
@REM set ACTIVITY_AGGREGATOR_SESSION_TIMEOUT_SECONDS_CONFIG=120

@echo on

call set-env.cmd
@REM set ACTIVITY_AGGREGATOR_CONSUMER_THREADS_COUNT=5


set ACTIVITY_AGGREGATOR_INPUT_TOPIC=%PEDESTRIANS_STREETS_TOPIC%
set ACTIVITY_AGGREGATOR_MOBILITY_TYPE=pedestrians
set ACTIVITY_AGGREGATOR_LOCATION_TYPE=street
set ACTIVITY_AGGREGATOR_PERSISTENCE_INTERVAL_SEC=20
for /l %%i in (1,1,1) do start /B  %EXECUTION_COMMAND%
set ACTIVITY_AGGREGATOR_PERSISTENCE_INTERVAL_SEC=


set ACTIVITY_AGGREGATOR_INPUT_TOPIC=%PEDESTRIANS_NEIGHBORHOODS_TOPIC%
set ACTIVITY_AGGREGATOR_MOBILITY_TYPE=pedestrians
set ACTIVITY_AGGREGATOR_LOCATION_TYPE=neighborhood
for /l %%i in (1,1,1) do start /B  %EXECUTION_COMMAND%


set ACTIVITY_AGGREGATOR_INPUT_TOPIC=%MOBILIZED_STREETS_TOPIC%
set ACTIVITY_AGGREGATOR_MOBILITY_TYPE=mobilized
set ACTIVITY_AGGREGATOR_LOCATION_TYPE=street
for /l %%i in (1,1,1) do start /B  %EXECUTION_COMMAND%


set ACTIVITY_AGGREGATOR_INPUT_TOPIC=%MOBILIZED_NEIGHBORHOODS_TOPIC%
set ACTIVITY_AGGREGATOR_MOBILITY_TYPE=mobilized
set ACTIVITY_AGGREGATOR_LOCATION_TYPE=neighborhood
for /l %%i in (1,1,1) do start /B  %EXECUTION_COMMAND%
