{
 "title": "Kafka Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Consumer Group Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Total Lag by Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_topic_partition_current_offset) - sum by (topic) (kafka_consumergroup_current_offset)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Rate - Other Topics (Aggregated by Topic)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{topic!~\"__consumer_offsets.*\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message Rate - Other Topics (By Partition)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_topic_partition_current_offset{topic!~\"__consumer_offsets.*\"}[5m])",
     "legendFormat": "{{topic}} - {{partition}}"
    }
   ]
  },
  {
   "title": "Message Rate - Consumer Offsets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_topic_partition_current_offset{topic=~\"__consumer_offsets.*\"}[5m])",
     "legendFormat": "{{topic}} - {{partition}}"
    }
   ]
  },
  {
   "title": "Topic Current Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset",
     "legendFormat": "{{topic}} - {{partition}}"
    }
   ]
  }
 ]
}