{
 "title": "Minimal Kafka Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Message Rate per Topic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages/sec" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{topic!~\"__consumer_offsets.*\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Actual Messages in Topics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Message Count" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partition_current_offset{topic!~\"__consumer_offsets.*\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Lag by Consumer Group",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Lag (messages)" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  }
 ]
}